meta:
  engine: 4.1.0
units:
  spacing: 1
  pad: 2

  push_x: .5U + .5spacing
  push_y: .5U + .5spacing

  U: 18.4

  # extra padding is helpful while prototyping, won't be in final pcb
  pad_x: push_x + pad
  pad_y: push_y + pad

  # 1.5U units
  x15u: U
  y15u: 26.5
  spread15u: 1.5U + spacing
  
  # 2U Units
  x2u: U
  y2u: 35.5
  spread2u: 2U - 2 - spacing

points:
  key:
    padding: U + spacing
    spread: U + spacing
    tags: 
      - key
  zones:
    matrix:
      key.spread: U + spacing
      anchor.shift: [50,-100] # Fix KiCad placement
      columns:
        control:
        pinky.key.stagger: .5 U
        ring.key.stagger: 0.25 U
        middle.key.stagger: 0.25 U
        index.key.stagger: -0.25 U
        inner.key.stagger: -.25 U
      rows:
        bottom:
        home:
        top:
        num:
    thumb:
      key.spread: U + spacing
      anchor:
        - ref: matrix_index_bottom
          shift: [5, -U - 20]
      columns:
        c0:
          key:
            shift: [0, .25U + .5spacing]
            splay: -10
            tags: key_15u_y
            
        c2:
          key:
            shift: [0, -.5U - .5spacing]
        c3:
          key:
            shift: [-U -spacing, .5U + .5spacing]
      rows: 
        r0:
outlines:
  keys:
    - what: rectangle
      where: true
      size: [14, 14]
      fillet: 0
  keycaps:
    - what: rectangle
      where: [key]
      size: [U, U]
    - what: rectangle
      where: [key_15u]
      size: [1.5U, U]
    - what: rectangle
      where: [key_15u_y]
      size: [U, 1.5U]
    - what: rectangle
      where: [key_2u]
      size: [x2u, y2u]
  board:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        # top of keyboard
        - ref: matrix_control_num
          shift: [-pad_x, pad_y]
        - ref: matrix_control_num
          shift: [push_x - pad, pad_y]

        - ref: matrix_pinky_num
          shift: [-push_x - pad, pad_y]
        - ref: matrix_pinky_num
          shift: [push_x - pad, pad_y]

        - ref: matrix_ring_num
          shift: [-push_x - pad, pad_y]
        - ref: matrix_ring_num
          shift: [push_x - pad, pad_y]
        
        - ref: matrix_middle_num
          shift: [-push_x - pad, pad_y]
        - ref: matrix_middle_num
          shift: [push_x + pad, pad_y]

        - ref: matrix_index_num
          shift: [-push_x + pad, pad_y]
        - ref: matrix_index_num
          shift: [push_x + pad, pad_y]

        - ref: matrix_inner_num
          shift: [-push_x + pad, pad_y]
        - ref: matrix_inner_num
          shift: [pad_x, pad_y]

        # wrap around thumb cluster
        - ref: matrix_inner_bottom
          shift: [pad_x, -push_y]
        - ref: thumb_c3_r0
          shift: [pad_x, push_y + pad]

        - ref: thumb_c2_r0
          shift: [pad_x, -pad_y]
        - ref: thumb_c2_r0
          shift: [-push_x - pad, -pad_y]

        - ref: thumb_c0_r0
          shift: [push_x - pad, -pad_y - .25U]
        - ref: thumb_c0_r0
          shift: [-push_x - pad, -pad_y - .25U]

        - ref: matrix_middle_bottom
          shift: [ push_x - pad, -pad_y]
        - ref: matrix_middle_bottom
          shift: [-push_x + pad, -pad_y]
        
        - ref: matrix_ring_bottom
          shift: [ push_x + pad, -pad_y]
        - ref: matrix_ring_bottom
          shift: [-push_x + pad, -pad_y]
        
        - ref: matrix_pinky_bottom
          shift: [push_x + pad, -pad_y]
        - ref: matrix_pinky_bottom
          shift: [-push_x + pad, -pad_y]

        - ref: matrix_control_bottom
          shift: [push_x + pad, -pad_y]
        - ref: matrix_control_bottom
          shift: [-pad_x, -pad_y]

  board_key_cutouts:
    - name: board
    - operation: subtract
      name: keys
  board_preview_keycaps:
    - name: board
    - operation: subtract
      name: keycaps

cases:
  plate:
    - name: board_key_cutouts
      extrude: 1.2

  # for prototyping / previewing the case
  case_mockup:
    - name: board_key_cutouts
      extrude: 5

  # plate_caps:

  # key_cutouts:
  #   - name: xl_board_left
  #   - operation: subtract
  #     name: keys